### ISSUE TITLE
Update data transfer to use power model

### ISSUE THREAD

**Issue by bokelley** [scope3data/methodology#112]
The current numbers we're using for data transfer don't pass the sniff test. The idea that it takes 0.1 kWh to deliver a GB of data implies that the energy use is 100W - if the data transfer took an hour. However, looking at Malmodin and other models of the actual data transmission infrastructure, this seems an order of magnitude too high. The "high" bandwidth model (6.67 mbps) is around 11.4W, and most residential broadband is significantly faster than this these days.

It seems like we should be using the power model to figure out the bandwidth cost (effectively, "how many seconds does it take to transfer"):

<img width="345" alt="CleanShot 2023-04-30 at 14 03 28@2x" src="https://user-images.githubusercontent.com/134922/235369011-b0b9378d-5b85-4b89-ac89-68d463db258d.png">

This is significantly lower than the numbers we are seeing today by a factor of 25. This feels much more reasonable!

**Comment by github-benjamin-davy** [comment]
Hello Brian, 

Gauthier Roussilhe has published a great write-up on the DIMPACT/Carbon Trust approach [here](https://gauthierroussilhe.com/articles/explications-sur-l-empreinte-carbone-du-streaming-et-du-transfert-de-donnees) detailing the different power factors for:
- core networks (common for all cases)
- access networks (different model for fixed and mobile networks)
- home router (only in the case of fixed networks)

<img width="939" alt="Screenshot 2023-05-02 at 11 05 17" src="https://user-images.githubusercontent.com/31283191/235625682-180dbd6c-e473-4fbf-bad3-8715d94da4df.png">

The bandwidth to consider should be adapted depending on the type of delivery I guess.

**Comment by github-benjamin-davy** [comment]
Hello @bokelley and @EmmaLouise2018 

While looking at [](https://github.com/scope3data/methodology/pull/125) I was finding the fixed electricity consumption rate chosen for fixed networks to be high compared to the study above. I might have missed something as well but did you use other research?

I'm concerned this could somewhat incentivize users to move delivery to mobile/cellular in certain cases, which isn't what we want from a global perspective (from different studies the footprint of fixed networks is less correlated with data usage compared to the one of cellular networks). Did you check the impact of this update on the current numbers? I would argue that once the fixed network is here we better be maximizing the use of it!

Also, it could be inconsistent with the figures used in the SRI dataset based on the ADEME ARCEP work and the associated public recommendation to mitigate the environmental impact of digital [](https://en.arcep.fr/news/press-releases/view/n/the-environment-050423.html) 

_"In January 2023, Arcep published [an FAQ](https://www.arcep.fr/demarches-et-services/utilisateurs/equipements-et-usages-numeriques-comment-limiter-mon-impact-environnemental-au-quotidien.html) for the general public on its website, offering tips and best practices for digital device users on how to curtail their environmental footprint. Drawing on the findings of its work, the Authority recommends, for instance, **opting for a fixed (fiber, ADSL) internet connection whenever possible**."_

Thanks for your thoughts on this!

**Comment by bokelley** [comment]
This is excellent - thank you @github-benjamin-davy! We are working on this in #125 and will continue to update as we get new data. I think we are still below SRI on mobile and trying to understand the gap.
