### ISSUE TITLE
Add validation on data yaml files 

### ISSUE THREAD

**Issue by EmmaLouise2018** [scope3data/methodology#51]
Add validation to be run before any PR merge to ensure:

- [ ] All yaml files are parsable/valid
- [ ] Depending on type have the required field (i.e. specify corporate type yaml files require template)

**Comment by mikkokotila** [comment]
In terms of validity checks, it would be a great start towards bullet-proofness to have validation tests treat each signal as an algebraic data type (adt), and check the validity on that basis. 

The adt could incorporate basics such as strict typing, acceptable values, etc. but could be extended to be as rich as it makes sense.

Basically, the validation tests fail whenever the requirements of each adt is not met.
