### ISSUE TITLE
Use SRI emissions factors for FR

### ISSUE THREAD

**Issue by bokelley** [scope3data/methodology#85]
Some small differences from our current calculations:
- Use a blended network and device type when unknown instead of a single decision → this is probably smart and we should do it. See lines 70 and 71, and lines 82-84.
- They split out the internet box, which is embedded in our fixed data transfer assumptions. Line 102 and 125.
- They use conventional model for everything - not sure we have to support this or not, but could be a toggle

What we would do is create a new templates directory `FR` that French organizations (IAB France, SRI) could manage, and override certain values (specifically kWh/GB lines 72 and 73) and device emissions (lines 97-102 and lines 120-125). For measurements run in France, we would use these values instead of the global defaults, and work with other countries to manage their own assumptions as well.

**Comment by bokelley** [comment]
Update - SRI plans to release their database in open source in early 2023, so we can grab these emissions factors then

**Comment by ronlissack** [comment]
Research from SRI 2.0 has been incorporated into our measurement.
