### ISSUE TITLE
Update google numbers to include accurate scope 1,2,3 AND scope 1,2

### ISSUE THREAD

**Issue by bokelley** [scope3data/methodology#87]

**Comment by ronlissack** [comment]
Google report provides scope 1,2 (market and location) and scope 3 total. Do we wish to include that data in the corporate yaml raw_facts section ?

**Comment by bokelley** [comment]
Our "standard" - which we are convening the climate advisory council to affirm - is that we should use location-based emissions and include scope 3 data in the value chain. Especially for tech companies, where scope 3 is 95% or more of the total footprint, I don't think it's reasonable to exclude. In addition, we need to have consistent scope 3 categories as otherwise it would be difficult to do apples-to-apples comparison. One thing we should factor in is potential duplication, for instance, if YouTube includes consumer device impact in scope 3, then we should make sure we're not also counting this in our model.

**Comment by github-benjamin-davy** [comment]
Hello, regarding how to assess Scope 3 for data centers this [OCP talk](https://www.youtube.com/watch?v=KFvcQMTFj3s) covers the different use cases and shares interesting data on how emissions are distributed.
